version: "3.9"

services:
  backend:
    build:
      context: ./laravel-backend
      dockerfile: Dockerfile
    container_name: laravel-backend
    ports:
      - "8000:8000"
    volumes:
      - ./laravel-backend:/var/www
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: projekat
      DB_USERNAME: root
      DB_PASSWORD: root
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./react-frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: projekat
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: